fullnameOverride: todogi-expo-app
environment: prod
replicaCount: 1

image:
  repository: ghcr.io/cantalay/todogi-app
  tag: "sha-430e75a"
  pullPolicy: IfNotPresent

registrySecret:
  enabled: true
  remoteKey: platform/registry/ghcr
  targetName: ghcr-pull

containerPort: 8080

runtimeConfig:
  EXPO_PUBLIC_API_URL: https://api.singlestranger.com
  EXPO_PUBLIC_AUTH_URL: https://auth.cantalay.com
  NODE_ENV: production

nginx:
  existingConfigMap: todogi-expo-app-nginx
  configRevision: "1"

autoscaling:
  enabled: false

podDisruptionBudget:
  enabled: false
