apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - certificate/certificate.yaml
  - ingress/ingress.yaml

# Özel nginx gerekmiyorsa bu bloğu ve nginx/ dizinini sil, values'tan nginx.existingConfigMap'i kaldır.
configMapGenerator:
  - name: hello-web-nginx
    files:
      - default.conf=nginx/default.conf

generatorOptions:
  disableNameSuffixHash: true
  labels:
    app.kubernetes.io/name: hello-web
    app.kubernetes.io/part-of: hello
    talay.io/environment: prod
