apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hello-api-tls
  labels:
    app.kubernetes.io/name: hello-api
    app.kubernetes.io/part-of: hello
    talay.io/environment: prod
spec:
  secretName: hello-api-tls
  dnsNames:
    - api.hello.cantalay.com
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt
  usages:
    - digital signature
    - key encipherment
