fullnameOverride: todogi-expo-app
environment: prod
replicaCount: 1

image:
  repository: ghcr.io/cantalay/todogi-app
  tag: "sha-7170121"
  digest: "sha256:27cedb0093e43c5327f71992b7599c6f8033c3c579f50be565a0679f0a9a3290"
  pullPolicy: IfNotPresent

registrySecret:
  enabled: true
  remoteKey: platform/registry/ghcr
  targetName: ghcr-pull

containerPort: 8080

runtimeConfig:
  EXPO_PUBLIC_API_URL: https://api.singlestranger.com
  EXPO_PUBLIC_AUTH_URL: https://auth.cantalay.com
  EXPO_PUBLIC_AUTH_REALM: todogi
  NODE_ENV: production

nginx:
  existingConfigMap: todogi-expo-app-nginx
  configRevision: "1"

autoscaling:
  enabled: false

podDisruptionBudget:
  enabled: false
