name: financefollower-analytics
environment: prod
namespace: financefollower-analytics
chartPath: charts/talay-service
valuesFile: apps/prod/financefollower/analytics/values.yaml
manifestsPath: apps/prod/financefollower/analytics
