name: financefollower-api
environment: prod
namespace: financefollower-api
chartPath: charts/talay-service
valuesFile: apps/prod/financefollower/api/values.yaml
manifestsPath: apps/prod/financefollower/api
