apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: financefollower-web
  labels:
    app.kubernetes.io/name: financefollower-web
    app.kubernetes.io/part-of: financefollower
    talay.io/environment: prod
spec:
  ingressClassName: traefik
  tls:
    - secretName: financefollower-web-tls
      hosts:
        - vita-pick.com
        - www.vita-pick.com
  rules:
    - host: vita-pick.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: financefollower-web
                port:
                  number: 80
    - host: www.vita-pick.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: financefollower-web
                port:
                  number: 80

