name: vitafinder-storefront
environment: prod
namespace: vitafinder-storefront
chartPath: charts/talay-web
valuesFile: apps/prod/vitafinder/storefront/values.yaml
manifestsPath: apps/prod/vitafinder/storefront
